tap "felixkratz/formulae"
tap "dimentium/autoraise"

brew "btop"
brew "beads"
brew "eza"
brew "fd"
brew "ripgrep"
brew "fzf"
brew "gh"
brew "git"
brew "gopls"
brew "lazygit"
brew "lua-language-server"
brew "neovim"
brew "node"
brew "opencode"
brew "pnpm"
brew "prettier"
brew "lua"
brew "playwright-cli"
brew "python"
brew "steipete/tap/remindctl"
brew "stow"
brew "starship"
brew "tmux"
brew "uv"
brew "zoxide"
brew "nmap"
brew "telnet"
brew "wireguard-tools"
brew "sketchybar"
brew "felixkratz/formulae/borders"
# CLI build, not the autoraiseapp cask: brew services runs it with no args,
# which is the only mode where AutoRaise reads ~/.config/AutoRaise/config
# (any CLI arg makes it ignore config files entirely).
brew "dimentium/autoraise/autoraise"
brew "gemini-cli"

cask "aerospace"
cask "bitwarden"
cask "claude-code"
cask "codex"
cask "font-jetbrains-mono-nerd-font"
cask "font-sketchybar-app-font"
cask "ghostty"
cask "karabiner-elements"
cask "keepingyouawake"
cask "localsend"
cask "raycast"
