schema_version = 1

[theme]
id = "osaka-jade"
name = "Osaka Jade"
variant = "dark"
source = "https://github.com/basecamp/omarchy"

[identifiers]
ghostty = "Osaka Jade"
nvim_colorscheme = "osaka-jade"
nvim_plugin = "st-eez/osaka-jade.nvim"
antigravity = "Ocean Green: Dark"
opencode = "osaka-jade"
obsidian = "Osaka Jade"

[palette]
bg0 = "#111c18"
bg1 = "#1a2520"
bg2 = "#23372b"
fg = "#c1c497"
grey = "#53685b"
red = "#ff5345"
orange = "#e5c736"
yellow = "#e5c736"
green = "#549e6a"
cyan = "#2dd5b7"
blue = "#509475"
magenta = "#d2689c"

[overrides.neovim]
dev = true

[overrides.obsidian]
variable_prefix = "osaka"
editor_color = "#23372b"
active_file_accent = "#549e6a"

[overrides.sketchybar]
highlight = "#549e6a"

[overrides.tmux]
thm_maroon = "#75bbb3"
thm_sky = "#8cd3cb"
thm_blue = "#acd4cf"
thm_lavender = "#75bbb3"
thm_mauve = "#2dd5b7"
thm_pink = "#d2689c"
thm_flamingo = "#db9f9c"
thm_rosewater = "#f6f5dd"
catppuccin_session_color = "#{?client_prefix,#{E:@thm_pink},#{E:@thm_green}}"
catppuccin_status_application_icon_bg = "#75bbb3"

[overrides.opencode_theme]
file = "osaka-jade.json"
